config/routes.rb
UserApp::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin518', as: 'rails_admin'
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :users

  get "users/new"

  root 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',    via: 'get'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://google.com/">Sydster</a>
    by Anthony Jones
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
  <header class="bg-white header header-md navbar navbar-fixed-top-xs box-shadow">
    <div class="navbar-header aside-md dk">
      <a class="btn btn-link visible-xs" data-toggle="class:nav-off-screen" data-target="#nav">
        <i class="fa fa-bars"></i> </a>

      <a href="index.html" class="navbar-brand">ECM</a>

      <a class="btn btn-link visible-xs" data-toggle="dropdown" data-target=".user">
        <i class="fa fa-cog"></i> </a>
    </div>
    <ul class="nav navbar-nav hidden-xs">
      <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="fa fa-th fa-lg"></i> </a>
        <section class="dropdown-menu aside-lg bg-white on animated fadeInLeft">
          <div class="row m-l-none m-r-none m-t m-b text-center">
            <div class="col-xs-4">
              <div class="padder-v"> <a href="#"> <span class="m-b-xs block"> <i class="i i-mail i-2x text-primary-lt"></i> </span> <small class="text-muted">Mailbox</small> </a> </div>
            </div>
            <div class="col-xs-4">
              <div class="padder-v"> <a href="#"> <span class="m-b-xs block"> <i class="i i-calendar i-2x text-danger-lt"></i> </span> <small class="text-muted">Calendar</small> </a> </div>
            </div>
            <div class="col-xs-4">
              <div class="padder-v"> <a href="#"> <span class="m-b-xs block"> <i class="i i-map i-2x text-success-lt"></i> </span> <small class="text-muted">Map</small> </a> </div>
            </div>
            <div class="col-xs-4">
              <div class="padder-v"> <a href="#"> <span class="m-b-xs block"> <i class="i i-paperplane i-2x text-info-lt"></i> </span> <small class="text-muted">Trainning</small> </a> </div>
            </div>
            <div class="col-xs-4">
              <div class="padder-v"> <a href="#"> <span class="m-b-xs block"> <i class="i i-images i-2x text-muted"></i> </span> <small class="text-muted">Photos</small> </a> </div>
            </div>
            <div class="col-xs-4">
              <div class="padder-v"> <a href="#"> <span class="m-b-xs block"> <i class="i i-clock i-2x text-warning-lter"></i> </span> <small class="text-muted">Timeline</small> </a> </div>
            </div>
          </div>
        </section>
      </li>
    </ul>
    <form class="navbar-form navbar-left input-s-lg m-t m-l-n-xs hidden-xs" role="search">
      <div class="form-group">
        <div class="input-group"> <span class="input-group-btn">
          <button type="submit" class="btn btn-sm bg-white b-white btn-icon"><i class="fa fa-search fa-lg"></i></button>
          </span>
          <input type="text" class="form-control input-sm no-border" placeholder="Search apps, projects...">
        </div>
      </div>
    </form>
    <ul class="nav navbar-nav navbar-right m-n hidden-xs nav-user user">
      <li class="hidden-xs"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="fa fa-comment-o fa-lg"></i> <span class="badge badge-sm up bg-danger count">2</span> </a>
        <section class="dropdown-menu aside-xl animated flipInY">
          <section class="panel bg-white">
            <header class="panel-heading b-light bg-light"> <strong>You have <span class="count">2</span> notifications</strong> </header>
            <div class="list-group list-group-alt"> <a href="#" class="media list-group-item"> <span class="pull-left thumb-sm"> <img src="images/a0.jpg" alt="John said" class="img-circle"> </span> <span class="media-body block m-b-none"> Use awesome animate.css<br>
              <small class="text-muted">10 minutes ago</small> </span> </a> <a href="#" class="media list-group-item"> <span class="media-body block m-b-none"> 1.0 initial released<br>
              <small class="text-muted">1 hour ago</small> </span> </a> </div>
            <footer class="panel-footer text-sm"> <a href="#" class="pull-right"><i class="fa fa-cog"></i></a> <a href="#notes" data-toggle="class:show animated fadeInRight">See all the notifications</a> </footer>
          </section>
        </section>
      </li>
      <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span class="thumb-sm avatar pull-left"> <%= gravatar_for current_user %>  </span> <%= current_user.name %> <b class="caret"></b> </a>
        <ul class="dropdown-menu animated fadeInRight">
          <span class="arrow top"></span>
          <li> <%= link_to 'Settings', edit_user_path(current_user) %> </li>
          <li> <%= link_to "Profile", current_user %> </li>
          <li> <a href="#"> <span class="badge bg-danger pull-right">3</span> Notifications </a> </li>
          <li> <a href="docs.html">Help</a> </li>
          <li class="divider"></li>
          <li><%= link_to "Logout", signout_path, method: "delete" %> </li>
        </ul>
      </li>
    </ul>
  </header>

app/views/layouts/_header_old.html.erb
<div id="section-topbar">
  <div id="topbar-inner">
    <div class="container">
      <%= link_to "sydster (beta)", root_path, id: "logo" %>
      <div class="row">
        <div class="dropdown">
          <ul id="nav" class="nav">
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>
              <% end %>
            </li>
            <li>
              <%= link_to help_path do %>
                  <i class="fa fa-search"></i>
              <% end %>
            </li>
            <% if signed_in? %>
                <li>
                  <%= link_to users_path do %>
                      <i class="fa fa-users"></i>
                  <% end %>
                </li>

                <li>
                  <%= link_to edit_user_path(current_user) do %>
                      <i class="fa fa-cogs"></i>
                  <% end %>
                </li>
                <li class="menu-text">
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
                <% else %>
                    <li class="menu-text"><%= link_to "Sign in", signin_path %></li>
                <% end %>
          </ul><!--/ uL#nav -->
        </div><!-- /.dropdown -->

        <div class="clear"></div>
      </div><!--/.row -->
    </div><!--/.container -->

    <div class="clear"></div>
  </div><!--/ #topbar-inner -->
</div><!--/ #section-topbar -->
<br />

app/views/layouts/_homeContent.html.erb
<%= yield %>

app/views/layouts/_homeHeader.html.erb
<header id="header" class="navbar navbar-fixed-top bg-primary dk" data-spy="affix" data-offset-top="1">
  <div class="container">
    <div class="navbar-header"> <a href="#" class="navbar-brand m-r-lg"><span class="text-lt">ECM</span></a> <button class="btn btn-primary btn-emtpy visible-xs" type="button" data-toggle="collapse" data-target=".navbar-collapse"> <i class="fa fa-bars"></i> </button> </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li> <a href="#howitworks" data-ride="scroll">Services</a> </li>
        <li> <a href="#features" data-ride="scroll">Owners</a> </li>
        <li> <a href="#pro" data-ride="scroll">Company</a> </li>
        <li> <a href="#download" data-ride="scroll">Contact Us</a> </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <div class="m-t-sm"><a href="signin.html" class="btn btn-link btn-sm">Sign in</a> or <a href="signup.html" class="btn btn-sm btn-success btn-rounded m-l"><strong>Sign up</strong></a></div>
        </li>
      </ul>
    </div>
  </div>
</header>

<a href="index.html" class="navbar-brand">
  <%= link_to(image_tag("logo.png", :class => "m-r-sm", :alt => "home image", :title => "ECM Logo")) %>
  ECM</a>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<% if signed_in? %>
<section>
  <section class="hbox stretch">
    <!-- .aside -->
    <aside class="bg-black aside-md hidden-print" id="nav">
      <section class="vbox">
        <section class="w-f scrollable">
          <div class="slim-scroll" data-height="auto" data-disable-fade-out="true" data-distance="0" data-size="10px" data-color="#333333">
            <div class="clearfix wrapper dk nav-user hidden-xs">
              <div class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span class="thumb avatar pull-left m-r"> <%= gravatar_for current_user %> <i class="on md b-black"></i> </span> <span class="hidden-nav-xs clear"> <span class="block m-t-xs"> <strong class="font-bold text-lt"><%= current_user.name %></strong> <b class="caret"></b> </span> <span class="text-muted text-xs block"><%= current_user.email %></span> </span> </a>
                <ul class="dropdown-menu animated fadeInRight m-t-xs">
                  <span class="arrow top hidden-nav-xs"></span>
                  <li> <a href="#">Settings</a> </li>
                  <li> <a href="profile.html">Profile</a> </li>
                  <li> <a href="#"> <span class="badge bg-danger pull-right">3</span> Notifications </a> </li>
                  <li> <a href="docs.html">Help</a> </li>
                  <li class="divider"></li>
                  <li> <a href="modal.lockme.html" data-toggle="ajaxModal" >Logout</a> </li>
                </ul>
              </div>
            </div>
            <!-- nav -->
            <nav class="nav-primary hidden-xs">
              <div class="text-muted text-sm hidden-nav-xs padder m-t-sm m-b-sm">Start</div>
              <ul class="nav nav-main" data-ride="collapse">
                <li > <a href="index.html" class="auto"> <i class="fa fa-bank"> </i> <span class="font-bold">Home</span> </a> </li>
                <li > <a href="#" class="auto"> <span class="pull-right text-muted"> <i class="fa fa-folder-o text"></i> <i class="fa fa-folder-open text-active"></i> </span> <b class="badge bg-danger pull-right">4</b> <i class="fa fa-money"> </i> <span class="font-bold">Loan Status</span> </a>
                  <ul class="nav dk">
                    <li > <a href="layout-color.html" class="auto"> <i class="fa fa-circle-thin"></i> <span>Color option</span> </a> </li>
                    <li > <a href="layout-hbox.html" class="auto"> <i class="fa fa-circle-thin"></i> <span>Hbox layout</span> </a> </li>
                  </ul>
                </li>
                <li > <a href="#" class="auto"> <span class="pull-right text-muted"> <i class="fa fa-folder-o text"></i> <i class="fa fa-folder-open text-active"></i> </span> <i class="fa fa-comments"> </i> <span class="font-bold">Messages</span> </a>
                  <ul class="nav dk">
                    <li > <a href="buttons.html" class="auto"> <i class="fa fa-circle-thin"></i> <span>Buttons</span> </a> </li>
                    <li > <a href="icons.html" class="auto"> <b class="badge bg-info pull-right">369</b> <i class="fa fa-circle-thin"></i> <span>Icons</span> </a> </li>
                    <li > <a href="grid.html" class="auto"> <i class="fa fa-circle-thin"></i> <span>Grid</span> </a> </li>
                    <li > <a href="widgets.html" class="auto"> <b class="badge bg-dark pull-right">8</b> <i class="fa fa-circle-thin"></i> <span>Widgets</span> </a> </li>
                    <li > <a href="components.html" class="auto"> <i class="fa fa-circle-thin"></i> <span>Components</span> </a> </li>
                    <li > <a href="list.html" class="auto"> <i class="fa fa-circle-thin"></i> <span>List group</span> </a> </li>
                    <li > <a href="#table" class="auto"> <span class="pull-right text-muted"> <i class="fa fa-folder-o text"></i> <i class="fa fa-folder-open text-active"></i> </span> <i class="i i-dot"></i> <span>Table</span> </a>
                      <ul class="nav dker">
                        <li > <a href="table-static.html"> <i class="fa fa-circle-thin"></i> <span>Table static</span> </a> </li>
                        <li > <a href="table-datatable.html"> <i class="fa fa-circle-thin"></i> <span>Datatable</span> </a> </li>
                      </ul>
                    </li>
                    <li > <a href="#form" class="auto"> <span class="pull-right text-muted"> <i class="fa fa-folder-o text"></i> <i class="fa fa-folder-open text-active"></i> </span> <i class="i i-dot"></i> <span>Form</span> </a>
                      <ul class="nav dker">
                        <li > <a href="form-elements.html"> <i class="fa fa-circle-thin"></i> <span>Form elements</span> </a> </li>
                        <li > <a href="form-validation.html"> <i class="fa fa-circle-thin"></i> <span>Form validation</span> </a> </li>
                        <li > <a href="form-wizard.html"> <i class="fa fa-circle-thin"></i> <span>Form wizard</span> </a> </li>
                      </ul>
                    </li>
                    <li > <a href="chart.html" class="auto"> <i class="fa fa-circle-thin"></i> <span>Chart</span> </a> </li>
                    <li > <a href="portlet.html" class="auto"> <i class="fa fa-circle-thin"></i> <span>Portlet</span> </a> </li>
                    <li > <a href="timeline.html" class="auto"> <i class="fa fa-circle-thin"></i> <span>Timeline</span> </a> </li>
                  </ul>
                </li>
                <li > <a href="#" class="auto"> <span class="pull-right text-muted"> <i class="fa fa-folder-o text"></i> <i class="fa fa-folder-open text-active"></i> </span> <i class="fa fa-legal"> </i> <span class="font-bold">Legal</span> </a>
                  <ul class="nav dk">
                    <li > <a href="profile.html" class="auto"> <i class="fa fa-circle-thin"></i> <span>Profile</span> </a> </li>
                    <li > <a href="invoice.html" class="auto"> <i class="fa fa-circle-thin"></i> <span>Invoice</span> </a> </li>
                    <li class="active"> <a href="intro.html" class="auto"> <i class="fa fa-circle-thin"></i> <span>Intro</span> </a> </li>
                    <li > <a href="master.html" class="auto"> <i class="fa fa-circle-thin"></i> <span>Master</span> </a> </li>
                    <li > <a href="gmap.html" class="auto"> <i class="fa fa-circle-thin"></i> <span>Google Map</span> </a> </li>
                    <li > <a href="jvectormap.html" class="auto"> <i class="fa fa-circle-thin"></i> <span>Vector Map</span> </a> </li>
                    <li > <a href="signin.html" class="auto"> <i class="fa fa-circle-thin"></i> <span>Signin</span> </a> </li>
                    <li > <a href="signup.html" class="auto"> <i class="fa fa-circle-thin"></i> <span>Signup</span> </a> </li>
                    <li > <a href="404.html" class="auto"> <i class="fa fa-circle-thin"></i> <span>404</span> </a> </li>
                  </ul>
                </li>
                <li > <a href="#" class="auto"> <span class="pull-right text-muted"> <i class="fa fa-folder-o text"></i> <i class="fa fa-folder-open text-active"></i> </span> <i class="fa fa-cloud-upload"> </i> <span class="font-bold">Upload Documents</span> </a>
                  <ul class="nav dk">
                    <li > <a href="mail.html" class="auto"> <b class="badge bg-success lt pull-right">2</b> <i class="fa fa-circle-thin"></i> <span>Mailbox</span> </a> </li>
                    <li > <a href="fullcalendar.html" class="auto"> <i class="fa fa-circle-thin"></i> <span>Calendar</span> </a> </li>
                  </ul>
                </li>
              </ul>
              <div class="line dk hidden-nav-xs"></div>
              <div class="text-muted text-xs hidden-nav-xs padder m-t-sm m-b-sm">Lables</div>
              <ul class="nav">
                <li> <a href="mail.html#work"> <i class="fa fa-circle-thin text-info-dk"></i> <span>Work space</span> </a> </li>
                <li> <a href="mail.html#social"> <i class="fa fa-circle-thin text-success-dk"></i> <span>Connection</span> </a> </li>
                <li> <a href="mail.html#projects"> <i class="fa fa-circle-thin text-danger-dk"></i> <span>Projects</span> </a> </li>
              </ul>
              <div class="text-muted text-xs hidden-nav-xs padder m-t-sm m-b-sm">Circles</div>
              <ul class="nav">
                <li> <a href="#"> <i class="fa fa-circle-thin text-success-lt"></i> <span>College</span> </a> </li>
                <li> <a href="#"> <i class="fa fa-circle-thin text-warning"></i> <span>Social</span> </a> </li>
              </ul>
            </nav>
            <!-- / nav -->
          </div>
        </section>
        <footer class="footer hidden-xs no-padder text-center-nav-xs"> <a href="modal.lockme.html" data-toggle="ajaxModal" class="btn btn-icon icon-muted btn-inactive pull-right m-l-xs m-r-xs hidden-nav-xs"> <i class="i i-logout"></i> </a> <a href="#nav" data-toggle="class:nav-xs" class="btn btn-icon icon-muted btn-inactive m-l-xs m-r-xs"> <i class="fa fa-arrow-circle-o-left fa-2x text"></i> <i class="fa fa-arrow-circle-o-right fa-2x text-active"></i> </a> </footer>
      </section>
    </aside>
    <!-- /.aside -->
    <section id="content">
      <section class="vbox">
        <header class="header bg-white b-b b-light">
          <p></p>
        </header>
        <section>
          <section class="hbox stretch">
            <section>
              <section class="vbox">
                <section class="scrollable wrapper">
                  <% flash.each do |key, value| %>
                      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
                  <% end %>
                  <%= yield %>
                  <%= debug(params) if Rails.env.testing? %>
                </section>
              </section>
            </section>

          </section>
        </section>
        <footer class="footer bg-white b-t b-light">
          <p>This is a footer</p>
        </footer>
      </section>
      <a href="#" class="hide nav-off-screen-block" data-toggle="class:nav-off-screen" data-target="#nav"></a> </section>
  </section>
</section>
<% else %>
    <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.testing? %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all",
                               "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= yield :head %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.testing? %>
    </div>
  </body>
</html>

app/views/layouts/application_old.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all",
                               "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= yield :head %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.testing? %>
    </div>
  </body>
</html>